### PR TITLE
Milestone-4

### PR DESCRIPTION
**Pull request by atoledo-ec**
## Milestone-4

For this branch, I implement the logic folder with two files: calculate and operate.
For the operate file I give the functionality to process math simple operation +, -, ÷, x and %.
And, for the calculate file I give the functionality to process the symbols as AC, +/- and the period(.).

### CODE REVIEW

**Review by teekaytech — CHANGES_REQUESTED** [review]
### Status: Invalid Code Review Request :x: 

__Hi @alejandrotoledoweb, I commend you for the great effort put into this project. However, I have to mark the project as invalid due to the following reason(s):__

- [ ] Some linter checks are not successful. For this project to be seen as completed, you have to ensure that all linter checks are running and pass successfully. At the moment, your Linters/ESlint is running but the checks are not successful. Kindly look into this.

**Note that you do not have to close this PR or open another one: this PR should be used for your subsequent submissions.**

**_This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!_**

* * *

**_You can ping me on Twitter (@ola_lere), Github(@teekaytech), or slack (@taofeekolalere ). Remember to always ask your questions within the PR as this can be seen by previous and next reviewers._**

Happy Coding :man_technologist:

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello @alejandrotoledoweb :wave:

__I must commend your efforts so far in this project. Here are the major highlights for me:__

- You've implemented all the specified requirements for this milestone :tada: 
- Your  Pull Request has a meaningful title and a brief description :ok_hand: 

__However, one main change is required before this milestone can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [ ] A general requirement for this project is to ensure that you have a descriptive README.md. Kindly update your Readme to suit this project.


**[ OPTIONAL CHANGES ]**

- [x] You may want to convert your `total` variable to a string. e.g.
` total = one.times(two).toString(); `


* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hello @alejandrotoledoweb  👋

**You've done pretty well here fixing a few issues raised in the previous review. 👌**

However, let's make a couple of changes.

- [x] It seems you failed to include `.eslintrc.json` and `stylelintrc.json` config files as stated [here](https://github.com/microverseinc/linters-config/tree/master/react-redux), please kindly do that, and ensure the project is properly linted.

### **STATUS: CHANGES REQUESTED** 👷‍♂️

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

**Comment by atoledo-ec** [comment]
Hello Mike.
I already added those files but, they suppose to be only locally. It has nothing to do with the workflows on Github.

**Review by mikenath223 — APPROVED** [review]
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

**Pull request merged**
